// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class Protocol : ProtocolBase {
	public static  Protocol Instance = new Protocol();
	private Protocol() {
		Protocol.SetProtocol<chat_msg> (chat_msg.Tag);
		Protocol.SetRequest<SprotoType.chat_msg.request> (chat_msg.Tag);

		Protocol.SetProtocol<handshake> (handshake.Tag);
		Protocol.SetResponse<SprotoType.handshake.response> (handshake.Tag);

		Protocol.SetProtocol<heartbeat> (heartbeat.Tag);

		Protocol.SetProtocol<login_account> (login_account.Tag);
		Protocol.SetRequest<SprotoType.login_account.request> (login_account.Tag);
		Protocol.SetResponse<SprotoType.login_account.response> (login_account.Tag);

		Protocol.SetProtocol<register_account> (register_account.Tag);
		Protocol.SetRequest<SprotoType.register_account.request> (register_account.Tag);
		Protocol.SetResponse<SprotoType.register_account.response> (register_account.Tag);

	}

	public class chat_msg {
		public const int Tag = 5;
	}

	public class handshake {
		public const int Tag = 1;
	}

	public class heartbeat {
		public const int Tag = 3;
	}

	public class login_account {
		public const int Tag = 4;
	}

	public class register_account {
		public const int Tag = 2;
	}

}